/**
 * Local (air-gapped) in-app notifications — Task 20.
 *
 * Notifications are generated by the online platform from cross-tenant events; in the air-gapped
 * build there is no such source, so the inbox is empty and marks are no-ops. Kept as functions so
 * the notifications UI renders cleanly offline instead of erroring. No network.
 */
import type { ApiNotificationList } from '@/lib/api-client'

export async function getLocalNotifications(): Promise<ApiNotificationList> {
  return { items: [], unreadCount: 0 }
}

export async function getLocalUnreadCount(): Promise<number> {
  return 0
}

export async function markLocalNotificationRead(): Promise<void> {
  /* no-op: no local notification source */
}

export async function markAllLocalNotificationsRead(): Promise<void> {
  /* no-op: no local notification source */
}
