-- Migration 003: Seed NIST 800-171 requirement families (14 families)
-- Source: bedrock-cmmc/prisma/seeds/nist-data.ts (families array)
-- Generated by: prisma/export-to-sql.ts

INSERT INTO "RequirementFamily" (id, code, name, description, "sortOrder", "conmonFrequency")
VALUES ('qcipxl9ns7bf6veloz7gvrcl', 'AC', 'Access Control', 'Limit system access to authorized users, processes acting on behalf of authorized users, and devices', 1, 'QUARTERLY')
ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description, "sortOrder" = EXCLUDED."sortOrder", "conmonFrequency" = EXCLUDED."conmonFrequency";

INSERT INTO "RequirementFamily" (id, code, name, description, "sortOrder", "conmonFrequency")
VALUES ('r8h1xvs2udhbfutyj3fi29mv', 'AT', 'Awareness and Training', 'Ensure that managers, system administrators, and users are aware of security risks', 2, 'ANNUAL')
ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description, "sortOrder" = EXCLUDED."sortOrder", "conmonFrequency" = EXCLUDED."conmonFrequency";

INSERT INTO "RequirementFamily" (id, code, name, description, "sortOrder", "conmonFrequency")
VALUES ('brtsd5wyobopirwh50itozy9', 'AU', 'Audit and Accountability', 'Create, protect, and retain system audit records to enable monitoring and analysis', 3, 'QUARTERLY')
ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description, "sortOrder" = EXCLUDED."sortOrder", "conmonFrequency" = EXCLUDED."conmonFrequency";

INSERT INTO "RequirementFamily" (id, code, name, description, "sortOrder", "conmonFrequency")
VALUES ('b3q0pld2f870q8luaschyjf1', 'CM', 'Configuration Management', 'Establish and maintain baseline configurations and inventories', 4, 'QUARTERLY')
ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description, "sortOrder" = EXCLUDED."sortOrder", "conmonFrequency" = EXCLUDED."conmonFrequency";

INSERT INTO "RequirementFamily" (id, code, name, description, "sortOrder", "conmonFrequency")
VALUES ('fu3myulj77ljn11wqqz0fo1h', 'IA', 'Identification and Authentication', 'Identify users, processes, and devices before authorizing access', 5, 'QUARTERLY')
ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description, "sortOrder" = EXCLUDED."sortOrder", "conmonFrequency" = EXCLUDED."conmonFrequency";

INSERT INTO "RequirementFamily" (id, code, name, description, "sortOrder", "conmonFrequency")
VALUES ('yb3m43pkqvruvm4dlsa2abnb', 'IR', 'Incident Response', 'Establish operational incident handling capability', 6, 'SEMI_ANNUAL')
ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description, "sortOrder" = EXCLUDED."sortOrder", "conmonFrequency" = EXCLUDED."conmonFrequency";

INSERT INTO "RequirementFamily" (id, code, name, description, "sortOrder", "conmonFrequency")
VALUES ('pjwkn0spg0ern7xrz8ly8ont', 'MA', 'Maintenance', 'Perform maintenance and manage repairs for organizational systems', 7, 'SEMI_ANNUAL')
ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description, "sortOrder" = EXCLUDED."sortOrder", "conmonFrequency" = EXCLUDED."conmonFrequency";

INSERT INTO "RequirementFamily" (id, code, name, description, "sortOrder", "conmonFrequency")
VALUES ('gtlmojg9be5ycpkavsbgoc0a', 'MP', 'Media Protection', 'Protect system media in both digital and non-digital formats', 8, 'QUARTERLY')
ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description, "sortOrder" = EXCLUDED."sortOrder", "conmonFrequency" = EXCLUDED."conmonFrequency";

INSERT INTO "RequirementFamily" (id, code, name, description, "sortOrder", "conmonFrequency")
VALUES ('d3figq9ry1v1z0cqo5cdgno5', 'PS', 'Personnel Security', 'Screen individuals before authorizing access to systems', 9, 'ANNUAL')
ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description, "sortOrder" = EXCLUDED."sortOrder", "conmonFrequency" = EXCLUDED."conmonFrequency";

INSERT INTO "RequirementFamily" (id, code, name, description, "sortOrder", "conmonFrequency")
VALUES ('swrx7nugncm7epap4zgijaut', 'PE', 'Physical Protection', 'Limit physical access to systems and the environments in which they operate', 10, 'SEMI_ANNUAL')
ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description, "sortOrder" = EXCLUDED."sortOrder", "conmonFrequency" = EXCLUDED."conmonFrequency";

INSERT INTO "RequirementFamily" (id, code, name, description, "sortOrder", "conmonFrequency")
VALUES ('zpw6zzbkw8tymcs6g71o1why', 'RA', 'Risk Assessment', 'Periodically assess risk to organizational operations and assets', 11, 'SEMI_ANNUAL')
ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description, "sortOrder" = EXCLUDED."sortOrder", "conmonFrequency" = EXCLUDED."conmonFrequency";

INSERT INTO "RequirementFamily" (id, code, name, description, "sortOrder", "conmonFrequency")
VALUES ('xsll1k7o159gmje5hbxbbi3q', 'CA', 'Security Assessment', 'Periodically assess security controls and develop plans of action', 12, 'ANNUAL')
ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description, "sortOrder" = EXCLUDED."sortOrder", "conmonFrequency" = EXCLUDED."conmonFrequency";

INSERT INTO "RequirementFamily" (id, code, name, description, "sortOrder", "conmonFrequency")
VALUES ('z7j8vl9gq5pwtf4bvtee7k5l', 'SC', 'System and Communications Protection', 'Monitor, control, and protect communications at system boundaries', 13, 'QUARTERLY')
ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description, "sortOrder" = EXCLUDED."sortOrder", "conmonFrequency" = EXCLUDED."conmonFrequency";

INSERT INTO "RequirementFamily" (id, code, name, description, "sortOrder", "conmonFrequency")
VALUES ('q9u578w0a1v75yjm4qm9ni8n', 'SI', 'System and Information Integrity', 'Identify, report, and correct system flaws in a timely manner', 14, 'QUARTERLY')
ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description, "sortOrder" = EXCLUDED."sortOrder", "conmonFrequency" = EXCLUDED."conmonFrequency";

