/**
 * Trigger a file download from a URL whose response sets
 * `Content-Disposition: attachment` (e.g. an S3 presigned URL generated by the
 * Go API). Uses a transient anchor click rather than window.open so the browser
 * starts the download without leaving a blank tab spinning on the attachment
 * response.
 */
export function triggerFileDownload(url: string, fileName?: string): void {
  if (typeof document === 'undefined') return
  const a = document.createElement('a')
  a.href = url
  if (fileName) a.download = fileName
  a.rel = 'noopener noreferrer'
  a.style.display = 'none'
  document.body.appendChild(a)
  a.click()
  document.body.removeChild(a)
}
